language: objective-c
script:
	- xctool -project Elixir.xcodeproj -scheme "Elixir" -sdk macosx10.10  -arch x86_64 build
	- xctool -project Elixir.xcodeproj -scheme "Elixir-iOS" -sdk iphonesimulator -arch i386 build